### ISSUE TITLE
Error:  The Parser function of type "table" is not defined.

### ISSUE THREAD

**Issue by fzsf163** [editor-js/awesome-editorjs#104]
The parser can not parse table.  How do you parse table? I am using remix js with ts and tailwind css.

import { OutputData } from "@editorjs/editorjs";
import editorJsHtml from "editorjs-html";

const EditorJsToHtml = editorJsHtml();

type Props = {
  data: OutputData;
};
type ParsedContent = string | JSX.Element;

export default function EJ_Renderer({ data }: Props) {
  const html = EditorJsToHtml.parse(data) as ParsedContent[];
  console.log("🚀 ~ EJ_Renderer ~ html:", html);  // 👈 this is where error comes from

  return (
    <div className="prose max-w-full" key={data.time}>
      {/* {html.map((item, index) => {
        if (typeof item === "string") {
          return (
            <div dangerouslySetInnerHTML={{ __html: item }} key={index}></div>
          );
        }
        return item;
      })} */} 👈 this code block destroys everything. Sometimes work though.
    </div>
  );
}

**Comment by talyguryn** [comment]
sorry for the long response. you need to create a task in the repository of the utility you are using.
see https://github.com/pavittarx/editorjs-html

also you can ask a question in the [Telegram chat for the Editor.js](https://t.me/codex_editor). there is a big community of developers
