### ISSUE TITLE
.gif support

### ISSUE THREAD

**Issue by butterup** [editor-js/awesome-editorjs#25]
Hey guys,

We're huge fans of editor js, we have it installed in our app https://tickr.co.uk

Just wondering, how can we support .gif functionality with editor js? I can't seem to find a plugin for this.

Would we need to build one ourselves?

Thanks

**Comment by talyguryn** [comment]
Hey @butterup,

You can use [@editor-js/image](https://github.com/editor-js/image) and set `types` param `image/gif` to allow this files choosing. We use this tool for uploading images and mp4 files in [codex.docs](https://github.com/codex-team/codex.docs) project.

https://github.com/codex-team/codex.docs/blob/e27bc523880897d9e189b208657c29720298733a/src/frontend/js/classes/editor.js#L46-L63

**Comment by butterup** [comment]
Wow thanks for the fast reply @talyguryn !
