### ISSUE TITLE
Is there any way to convert HTML to block data?

### ISSUE THREAD

**Issue by jigneshzala** [editor-js/awesome-editorjs#34]
I have one large set of HTML data and won't use Editors js, but how can I convert HTML to data blocks, is there any workaround available?

**Comment by Bashamega** [comment]
Hello:)
You  can use this code to convert them
`
const editor = new EditorJS({
  ...
  onReady: async () => {
    if (dataIsHtml) {
      await editor.blocks.renderFromHTML(data);
    }
  },
  ...
});`
If you want to find out more you can read this issue. [Here](https://github.com/codex-team/editor.js/issues/1232)
