### ISSUE TITLE
How to implement Editor.js in nextjs?

### ISSUE THREAD

**Issue by AffanTheBest** [editor-js/awesome-editorjs#46]
I tried to implement Editor.js in Nextjs but I failed to do it.

Here is my code.
```js
import EditorJS from '@editorjs/editorjs';
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [editor, setEditor] = useState();
  useEffect(() => {
    setEditor(new EditorJS());
  }, []);
  return <div className={styles.container}></div>;
}
```

Error:
```
Server Error
ReferenceError: window is not defined
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

Can someone help me to implement EditorJs in NextJs?

Code: [https://stackblitz.com/edit/nextjs-editorjs?devtoolsheight=33&file=pages/index.js](https://stackblitz.com/edit/nextjs-editorjs?devtoolsheight=33&file=pages/index.js)

**Comment by talyguryn** [comment]
To report and resolve any problems with Editor.js, please open issues in the core repo.

https://github.com/codex-team/editor.js

Thank you.

**Comment by AffanTheBest** [comment]
Got it working via **Next Dynamic Import**.

NextJs Code:
```js
import dynamic from 'next/dynamic';

const EditorJs = dynamic(import('react-editor-js'), {
  ssr: false,
  loading: () => <p>Loading ...</p>,
});

const Editor = () => <EditorJs />

export default Editor;
```
