### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by PythonLinks** [editor-js/awesome-editorjs#52]
For this item. 
editorjs-social-post-plugin — embed uploaded posts from different social media platforms to Editor.js

Thanks for this great service, and softwrae.

**Comment by ndsvw** [comment]
Found more:
- [ ] https://github.com/ranemihir/editorjs-github-gist-plugin (file: README.md, status code: 404)
- [ ] https://github.com/ranemihir/editorjs-social-post-plugin (file: README.md, status code: 404)
- [ ] https://djit.su (file: README.md, error: CERT_HAS_EXPIRED)
- [ ] https://appunti.app (file: README.md, error: ECONNRESET)
- [ ] https://OmniaWrite.com (file: README.md, status code: 404)

**Comment by talyguryn** [comment]
@PythonLinks @ndsvw thanks for your attention
