### ISSUE TITLE
Hover triggers onChange

### ISSUE THREAD

**Issue by morsecoding** [editor-js/awesome-editorjs#80]
When any part of the table is in focus, for example if the cursor is in a cell, onChange() gets called whenever you hover/move over any part of the table. Thus simply dragging the mouse over different parts of the table, without ever clicking, will fire multiple onChange events.

In my case, I have embedded EditorJS in a macOS app WKWebView (Safari) and signal the app for changes through this event so I can do work in the app. The excessive calls makes it impossible to know when a true change actually occurs.

**Comment by talyguryn** [comment]
not for this repo. please use [codex-team/editor.js](https://github.com/codex-team/editor.js) repo if you want to report an issue about editor
